"""Trivial primality test — good enough for the small primes generated by
:meth:`implementations.regev.Regev.generate_a`.
"""


def is_prime(num: int) -> bool:
    if num < 2:
        return False
    for i in range(2, num):
        if num % i == 0:
            return False
    return True
